# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "uas" ];
      kernelModules = [];
    };
    kernelModules = [ ];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      # Required permissions for sshd to be happy
      options = [ "defaults" "size=256M" "mode=755" ];
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

    "/nix" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "nodiratime" "compress=zstd" "ssd" ];
    };

    "/state" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "btrfs";
      options = [ "subvol=state" "noatime" "nodiratime" "compress=zstd" "ssd" ];
      neededForBoot = true;
    };

    "/etc/nixos" = {
      device = "/state/etc/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

    "/var/log" = {
      device = "/state/var/log";
      fsType = "none";
      options = [ "bind" ];
      depends = [ "/state" ];
      neededForBoot = true;
    };

    "/etc/ssh" = {
      device = "/state/etc/ssh";
      fsType = "none";
      options = [ "bind" ];
    };
  };

  swapDevices = [{ device = "/dev/disk/by-label/swap"; }];

}
