{ config, pkgs, ... }:

# This module is an attempt to build a minimal kernel that includes the
# submitted driver for the Sony IMX708 camera sensor, the downstream driver for
# the DW9817 voice coil motor for lens autofocus control, and the submitted ISP
# driver for hardware debayer: imx708, dw9807-vcm and bcm2835-isp (with
# associated changes to other drivers). imx708 and dw9807-vcm can be built as
# external modules, but for bcm2835-isp a lot of header changes are necessary,
# changing the ABI.

let
  inherit (pkgs) fetchurl fetchpatch;

  pkgs' = import pkgs.path {
    crossSystem = "aarch64-linux";
    localSystem = "x86_64-linux";
  };
in

{
  environment.systemPackages = [
    pkgs.v4l-utils
    pkgs.i2c-tools
    pkgs.dtc
    pkgs.libgpiod

    (pkgs'.libcamera.overrideAttrs (prevAttrs: {
      patches = prevAttrs.patches or [] ++ [
        (fetchurl {
          name = "0001-Raspberry-Pi-Update-VC4-pipeline-for-upstream.diff";
          url = "https://github.com/jailuthra/libcamera/commit/dd988bc1c0e9c17eb2b8dfaf2d7115797a9c46f4.diff";
          hash = "sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=";
        })
        (fetchurl {
          name = "0002-pipeline-raspberrypi-vc4-Configure-format-on-Unicam-subdev.diff";
          url = "https://github.com/jailuthra/libcamera/commit/ac81cd1855e6445ae399f81fa612e535164277d5.diff";
          hash = "sha256-dH0ZbDnTim8I/jn+NnttWD4smX8Mh7W1mLIWT3yIpoM=";
        })
        (fetchurl {
          name = "0003-include-uapi-Drop-controls-for-VC4-ISP-params.diff";
          url = "https://github.com/jailuthra/libcamera/commit/12744e08b9656f6353ff51f47bf548d262b05582.diff";
          hash = "sha256-00Mgi9+lZvoyZGkDFbJ1ZvY0jHGs+rXIqHS6pUdZrls=";
        })
        (fetchurl {
          name = "0004-pipeline-ipa-rpi-vc4-Use-extensible-parameter-buffers-for-ISP-configuration.diff";
          url = "https://github.com/jailuthra/libcamera/commit/b8f69a665b2bca50d91f2a0217b03d62d30468df.diff";
          hash = "sha256-xAmO2BJ1pEsikbHE8XZqVXF0efCyXT0yRBtkguptmsY=";
        })
      ];
    }))
  ];

  hardware.deviceTree.overlays = [
    {
      name = "imx708-overlay";
      dtsFile = ./imx708.dtso;
    }
  ];

  boot.kernelParams = [ "cma=128M" ];

  boot.kernelPackages = pkgs'.linuxPackages_custom {
    inherit (pkgs.linuxKernel.kernels.linux_testing) version src;

    # Minimal config is generated by selecting the config symbols with
    # menuconfig/nconfig and running savedefconfig:
    # $ make ARCH=arm64 nconfig
    # $ make ARCH=arm64 savedefconfig
    configfile = let makeTarget = "alldefconfig"; in (pkgs'.linuxKernel.linuxConfig {
      inherit (pkgs'.linuxKernel.kernels.linux_testing) version src;
      inherit (config.boot) kernelPatches;
      inherit makeTarget;
    }).overrideAttrs {
      buildPhase = ''
        make \
          ARCH=${pkgs.stdenv.hostPlatform.linuxArch} \
          HOSTCC=${pkgs.buildPackages.stdenv.cc.targetPrefix}gcc \
          KCONFIG_ALLCONFIG=${./minimal.config} \
          ${makeTarget}
      '';
    };

    # If false, CONFIG_MODULES is interpreted as false, kernel modules are not
    # installed and the pkgs/build-support/kernel/modules-closure.sh script
    # fails early.
    allowImportFromDerivation = true;
  };

  # INFO: fetchpatch, fetchpatch2 and `patch` create false positive patch
  # conflicts - the fetchers strip file rename information, reorder hunks and
  # do other nasty things (like silently dropping hunks... wtf?), causing
  # patching to fail when it otherwise would not - this can be worked around
  # using fetchurl, but `patch` support for renames is not perfect either.
  # See https://github.com/NixOS/nixpkgs/issues/32084.
  boot.kernelPatches = map (p: { name = if p ? name then p.name else baseNameOf p; patch = p; }) [
    ## Start of bcm2835-isp patches.

    # [v3,0/6] platform/raspberrypi: Add Broadcom Videocore shared memory support
    # https://patchwork.kernel.org/cover/14134951
    (fetchurl {
      name = "0001-v3-1-6-platform-raspberrypi-vchiq-mmal-Reset-buffers_with_vpu-on-port_enable.diff";
      url = "https://patchwork.kernel.org/patch/14693554/raw";
      hash = "sha256-cgmGf2krvZUxHZvTpF6nrws3njBmi28vBB4bpUaxfy8=";
    })
    (fetchurl {
      name = "0001-v3-2-6-platform-raspberrypi-vchiq-Store-audio-device-in-driver-management-struct.diff";
      url = "https://patchwork.kernel.org/patch/14693555/raw";
      hash = "sha256-3o09rlBTh3h0I3/L2UCp/9bL/J32mEZaP8IyABVgfxo=";
    })
    (fetchurl {
      name = "0003-v3-3-6-platform-raspberrypi-Add-VideoCore-shared-memory-support.diff";
      url = "https://patchwork.kernel.org/patch/14693556/raw";
      hash = "sha256-olU0TJobHWLlYTdKcMqpWbo6PnNnifNwddHhwTvcoqk=";
    })
    (fetchurl {
      name = "0004-v3-4-6-platform-raspberrypi-vchiq-mmal-Use-vc-sm-cma-to-support-zero-copy.diff";
      url = "https://patchwork.kernel.org/patch/14693557/raw";
      hash = "sha256-uEeXO17DEZLm1NpWEpoyPkgfXcnbazs5FcbK3Kpe440=";
    })
    (fetchurl {
      name = "0005-v3-5-6-platform-raspberrypi-vchiq-mmal-Support-sending-data-to-MMAL-ports.diff";
      url = "https://patchwork.kernel.org/patch/14693558/raw";
      hash = "sha256-Bd5rSI1dcihmc9VuAk1D1eScyqzqK14lNXo57p+5ulE=";
    })
    (fetchurl {
      name = "0006-v3-6-6-platform-raspberrypi-vchiq-Register-vc-sm-cma-as-a-platform-driver.diff";
      url = "https://patchwork.kernel.org/patch/14693559/raw";
      hash = "sha256-2oh1CEggAT1vWat7dJZs31ShS/InmQp8if8kncgOP0Q=";
    })

    # [v3,0/9] media: Add support for Broadcom/RPi BCM2835 ISP
    # https://patchwork.kernel.org/cover/14134952
    (fetchurl {
      name = "0007-v3-1-9-platform-raspberrypi-vchiq-mmal-Include-missing-headers.diff";
      url = "https://patchwork.kernel.org/patch/14693563/raw";
      hash = "sha256-cRFfxP5x5WMU3DXJNomVPLQoJnnQXO5txlkcehV3/C8=";
    })
    (fetchurl {
      name = "0008-v3-2-9-platform-raspberrypi-vchiq-mmal-Move-headers-to-include-linux.diff";
      url = "https://patchwork.kernel.org/patch/14693564/raw";
      hash = "sha256-QajIh0ttIovMRjVh5ah597SA7vli0IKa3vaV1ZKH2iA=";
    })
    (fetchurl {
      name = "0009-v3-3-9-platform-raspberrypi-vchiq-mmal-Support-ISP-parameters-and-stats.diff";
      url = "https://patchwork.kernel.org/patch/14693565/raw";
      hash = "sha256-EeC5xrsytTde89w2/zbM4rIFn69M/3MCbc+1RAKmJKg=";
    })
    (fetchurl {
      name = "0010-v3-4-9-platform-raspberrypi-vchiq-mmal-Support-bayer-and-gray-formats.diff";
      url = "https://patchwork.kernel.org/patch/14693566/raw";
      hash = "sha256-W4ABAooN7Zz1Q0nbyj8DITuzqoNdcVoo/Uxnyib+h9Y=";
    })
    (fetchurl {
      name = "0011-v3-5-9-platform-raspberrypi-vchiq-Add-helpers-for-vchiq-driver-data.diff";
      url = "https://patchwork.kernel.org/patch/14693567/raw";
      hash = "sha256-BelB1SRe0SOP2vpft9etnHZnYpC8RteqhP9BfnXvZXE=";
    })
    (fetchurl {
      name = "0012-v3-6-9-media-videobuf2-Allow-exporting-of-a-struct-dmabuf.diff";
      url = "https://patchwork.kernel.org/patch/14693568/raw";
      hash = "sha256-aFKnBMp55xzW67uANxGlqprZtPvmqq12oxSSKjggXWk=";
    })
    (fetchurl {
      name = "0013-v3-7-9-media-platform-broadcom-Move-unicam-driver-to-subdir.diff";
      url = "https://patchwork.kernel.org/patch/14693569/raw";
      hash = "sha256-0IS232DtoHfuC/5KETH631Gng3xcVK0X2rrUXKHsFiI=";
    })
    (fetchpatch {
      name = "0014-v3-8-9-media-platform-broadcom-Add-bcm2835-isp-driver.diff";
      url = "https://patchwork.kernel.org/patch/14693571/raw";
      hash = "sha256-P3ghkLuDHXkRXluUEDEeO3CFmJw8x/LnlqMPPVbYgYk=";
      excludes = [
        "Documentation/admin-guide/media/v4l-drivers.rst"
      ];
    })
    (fetchurl {
      name = "0015-v3-9-9-platform-raspberrypi-vchiq-Load-bcm2835_isp-driver-from-vchiq.diff";
      url = "https://patchwork.kernel.org/patch/14693570/raw";
      hash = "sha256-P4XXKUQdF/MeLseQwyHIue856c/+PxM0CFzCprj6RUo=";
    })

    # clk: bcm: rpi: Mark ISP clock as critical
    # https://patchwork.kernel.org/patch/14287908/
    # https://github.com/raspberrypi/linux/issues/7100
    (fetchurl {
      name = "0016-clk-bcm-rpi-Mark-ISP-clock-as-critical.diff";
      url = "https://patchwork.kernel.org/patch/14287908/raw";
      hash = "sha256-RRqqC2rOmzZkDKBSB2WwgubPJTx0ZXcZ7z3ErjLi3bs=";
    })

    ## End of bcm2835-isp patches.
    ## Start of dw9817 patches.

    # Patches taken from the rpi-6.18.y branch.
    (fetchurl {
      name = "0017-media-dw9807-vcm-Add-support-for-DW9817-bidirectional-VCM-driver.diff";
      url = "https://github.com/raspberrypi/linux/commit/8e84b3a0a18c88cb399ade64d65710867d815cfc.diff";
      hash = "sha256-p4rrvfNosLO6FW0d1LAUHC69zSKRrYAoakaFc5WODZ4=";
    })
    (fetchurl {
      name = "0018-media-dt-bindings-Add-regulator-to-dw9807-vcm.diff";
      url = "https://github.com/raspberrypi/linux/commit/c6ff51571bd94b0202a30c1b4791172e28604879.diff";
      hash = "sha256-AOcCD9/LKBf+H5bSpdJ/jqi01/BUvR8RC2+SqRo0v1I=";
    })
    (fetchurl {
      name = "0019-media-dw9807-vcm-Add-regulator-support-to-the-driver.diff";
      url = "https://github.com/raspberrypi/linux/commit/2dbd8f2b2bdea951afe00970589b82035f4fd2bd.diff";
      hash = "sha256-w9qT/C+pRrYnVjT4yh2JmWtuy83bvXb4/LB/x9/L10k=";
    })
    (fetchurl {
      name = "0020-media-dw9807-vcm-Smooth-the-first-user-movement-of-the-lens.diff";
      url = "https://github.com/raspberrypi/linux/commit/4126e8b2c2e4919d9c300ac3e89503e7ea552fb4.diff";
      hash = "sha256-LanmafCiFD4hpdmfSK+XRvvRv5OuyKzQyqWEBiZGnNc=";
    })

    ## End of dw9817 patches.
    ## Start of imx708 patches.

    # [v2,0/3] media: Add bindings and driver for Sony IMX708
    # https://patchwork.kernel.org/cover/14140778
    (fetchurl {
      name = "0021-v2-1-3-dt-bindings-media-i2c-Add-imx708-image-sensor.diff";
      url = "https://patchwork.kernel.org/patch/14737302/raw";
      hash = "sha256-CQDNP7lV4Pj98rVCk8tFlXAvvkjq5ucRWfJFnXsgAFo=";
    })
    (fetchurl {
      name = "0022-v2-2-3-media-ccs-pll-Support-optional-input-for-VT-pixel-rate.diff";
      url = "https://patchwork.kernel.org/patch/14737303/raw";
      hash = "sha256-aNwM78uxFHE18wPqlu0UodWEcXT6wcjyl/vZmjUSG4o=";
    })
    (fetchpatch {
      name = "0023-v2-3-3-media-i2c-Add-a-driver-for-Sony-IMX708.diff";
      url = "https://patchwork.kernel.org/patch/14737304/raw";
      hash = "sha256-s/5ipai/QoffBNQZBwO3GEWc8WfEQwbgt+lAuUbmi3o=";
      excludes = [
        "drivers/media/i2c/Makefile"
      ];
    })
    ./0024-fixup-imx708-makefile.diff

    ## End of imx708 patches.
  ];
}
